apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
commonLabels:
  app: celestelopezgarrido-my-app
  app.kubernetes.io/instance: celestelopezgarrido-my-app-instance
  app.kubernetes.io/name: celestelopezgarrido-my-app
images:
- name: quay.io/upslopeio/express-sample-app
  newName: quay.io/celestelopezgarrido/express-sample-app
  newTag: d90c742ee626048c4d1e2032eb836255e4036561
